### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-freeze#16]
When can we expect web support for this awesome library?

**Comment by nandorojo** [comment]
Shouldn’t it already work for web?

**Comment by nandorojo** [comment]
The code is all JS: https://github.com/software-mansion/react-freeze/blob/main/src/index.tsx

**Comment by Hirbod** [comment]
I think it’s react-native-screens that has to support it for web.

**Comment by hbomatt** [comment]
It's simple to use without `react-native-screens` on Web, just wrap your screen children in `<Freeze />` and toggle it between frozen/thawed by checking your navigation state to determine if the screen instance is the current or previous screen (those should be thawed).

**Comment by tiaanduplessis** [comment]
The `react-native-screens` support isn't required for web. Using the `Freeze` component is working for me.
