### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by henkean** [software-mansion/react-freeze#25]
When react-freeze gets installed it creates a warning in projects that use react ^18.0.0:

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-freeze@1.0.0
npm WARN Found: react@18.0.0
npm WARN node_modules/react
npm WARN   react@"^18.0.0" from the root project
npm WARN   10 more (@react-navigation/bottom-tabs, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^17.0.0" from react-freeze@1.0.0
npm WARN node_modules/react-native-screens/node_modules/react-freeze
npm WARN   react-freeze@"^1.0.0" from react-native-screens@3.15.0
npm WARN   node_modules/react-native-screens
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^17.0.0" from react-freeze@1.0.0
npm WARN   node_modules/react-native-screens/node_modules/react-freeze
npm WARN     react-freeze@"^1.0.0" from react-native-screens@3.15.0
npm WARN     node_modules/react-native-screens

Are there any plans to update to react 18?

**Comment by kacperkapusciak** [comment]
It should be now fixed in the newest version of the package.

Cheers
